<?php

require_once dirname(__FILE__).'/../lib/quizz_questionGeneratorConfiguration.class.php';
require_once dirname(__FILE__).'/../lib/quizz_questionGeneratorHelper.class.php';

/**
 * quizz_question actions.
 *
 * @package    cms
 * @subpackage quizz_question
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class quizz_questionActions extends autoQuizz_questionActions
{

    public function preExecute()
    {
        parent::preExecute(); // TODO: Change the autogenerated stub
        $filters = $this->getFilters();
        if(empty($filters['quizz_id'])){
            return $this->redirect('quizz/index');
        }
        $this->Quizz = Q::f('Quizz', $filters['quizz_id']);
        if(!$this->Quizz || !$this->getUser()->isMy($this->Quizz)){
            return $this->redirect('quizz/index');
        }
    }

	public function executeDeleteQuestionAnswer(sfWebRequest $request) {
		
		$id = $request->getParameter('id');
		$Answer = Q::f('QuizzQuestionAnswer', $id);
		if($Answer){
			$Answer->delete();
		}
		$this->getUser()->setFlash('notice', 'Answer has been deleted');
		return $this->redirect($request->getReferer());
		
	}

    public function executeBack(){
        return $this->redirect('quizz/index');
    }
}
