<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Todo', 'doctrine');

/**
 * BaseTodo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $status
 * 
 * @method string getName()   Returns the current record's "name" value
 * @method enum   getStatus() Returns the current record's "status" value
 * @method Todo   setName()   Sets the current record's "name" value
 * @method Todo   setStatus() Sets the current record's "status" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTodo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('todo');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'open',
              1 => 'closed',
             ),
             'default' => 'open',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}