<?php

/**
 * BaseQuizzQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quizz_id
 * @property string $name
 * @property enum $answer_mode
 * @property string $comment
 * @property Quizz $Quizz
 * @property Doctrine_Collection $Answers
 * 
 * @method integer             getQuizzId()     Returns the current record's "quizz_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method enum                getAnswerMode()  Returns the current record's "answer_mode" value
 * @method string              getComment()     Returns the current record's "comment" value
 * @method Quizz               getQuizz()       Returns the current record's "Quizz" value
 * @method Doctrine_Collection getAnswers()     Returns the current record's "Answers" collection
 * @method QuizzQuestion       setQuizzId()     Sets the current record's "quizz_id" value
 * @method QuizzQuestion       setName()        Sets the current record's "name" value
 * @method QuizzQuestion       setAnswerMode()  Sets the current record's "answer_mode" value
 * @method QuizzQuestion       setComment()     Sets the current record's "comment" value
 * @method QuizzQuestion       setQuizz()       Sets the current record's "Quizz" value
 * @method QuizzQuestion       setAnswers()     Sets the current record's "Answers" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizzQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quizz_question');
        $this->hasColumn('quizz_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('answer_mode', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'select',
              1 => 'select_other',
              2 => 'other',
             ),
             'default' => 'select',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quizz', array(
             'local' => 'quizz_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('QuizzQuestionAnswer as Answers', array(
             'local' => 'id',
             'foreign' => 'quizz_question_id'));
    }
}