<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EmailError', 'doctrine');

/**
 * BaseEmailError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email_from
 * @property string $email_to
 * @property string $subject
 * @property string $body
 * @property string $cc
 * @property string $file
 * @property string $errmes
 * 
 * @method string     getEmailFrom()  Returns the current record's "email_from" value
 * @method string     getEmailTo()    Returns the current record's "email_to" value
 * @method string     getSubject()    Returns the current record's "subject" value
 * @method string     getBody()       Returns the current record's "body" value
 * @method string     getCc()         Returns the current record's "cc" value
 * @method string     getFile()       Returns the current record's "file" value
 * @method string     getErrmes()     Returns the current record's "errmes" value
 * @method EmailError setEmailFrom()  Sets the current record's "email_from" value
 * @method EmailError setEmailTo()    Sets the current record's "email_to" value
 * @method EmailError setSubject()    Sets the current record's "subject" value
 * @method EmailError setBody()       Sets the current record's "body" value
 * @method EmailError setCc()         Sets the current record's "cc" value
 * @method EmailError setFile()       Sets the current record's "file" value
 * @method EmailError setErrmes()     Sets the current record's "errmes" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmailError extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email_error');
        $this->hasColumn('email_from', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_to', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('cc', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('errmes', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}