<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserConfigSettings', 'doctrine');

/**
 * BaseUserConfigSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $receive_notification_quizz_taken
 * @property string $top_logo_image
 * @property string $logo_text
 * @property string $html_title
 * @property string $homepage_text
 * @property string $card_info
 * @property string $footer_info
 * @property string $email
 * @property string $phone
 * @property string $skype
 * @property string $facebook
 * @property string $website
 * @property string $youtube
 * @property string $image
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()                           Returns the current record's "user_id" value
 * @method boolean            getReceiveNotificationQuizzTaken()    Returns the current record's "receive_notification_quizz_taken" value
 * @method string             getTopLogoImage()                     Returns the current record's "top_logo_image" value
 * @method string             getLogoText()                         Returns the current record's "logo_text" value
 * @method string             getHtmlTitle()                        Returns the current record's "html_title" value
 * @method string             getHomepageText()                     Returns the current record's "homepage_text" value
 * @method string             getCardInfo()                         Returns the current record's "card_info" value
 * @method string             getFooterInfo()                       Returns the current record's "footer_info" value
 * @method string             getEmail()                            Returns the current record's "email" value
 * @method string             getPhone()                            Returns the current record's "phone" value
 * @method string             getSkype()                            Returns the current record's "skype" value
 * @method string             getFacebook()                         Returns the current record's "facebook" value
 * @method string             getWebsite()                          Returns the current record's "website" value
 * @method string             getYoutube()                          Returns the current record's "youtube" value
 * @method string             getImage()                            Returns the current record's "image" value
 * @method sfGuardUser        getUser()                             Returns the current record's "User" value
 * @method UserConfigSettings setUserId()                           Sets the current record's "user_id" value
 * @method UserConfigSettings setReceiveNotificationQuizzTaken()    Sets the current record's "receive_notification_quizz_taken" value
 * @method UserConfigSettings setTopLogoImage()                     Sets the current record's "top_logo_image" value
 * @method UserConfigSettings setLogoText()                         Sets the current record's "logo_text" value
 * @method UserConfigSettings setHtmlTitle()                        Sets the current record's "html_title" value
 * @method UserConfigSettings setHomepageText()                     Sets the current record's "homepage_text" value
 * @method UserConfigSettings setCardInfo()                         Sets the current record's "card_info" value
 * @method UserConfigSettings setFooterInfo()                       Sets the current record's "footer_info" value
 * @method UserConfigSettings setEmail()                            Sets the current record's "email" value
 * @method UserConfigSettings setPhone()                            Sets the current record's "phone" value
 * @method UserConfigSettings setSkype()                            Sets the current record's "skype" value
 * @method UserConfigSettings setFacebook()                         Sets the current record's "facebook" value
 * @method UserConfigSettings setWebsite()                          Sets the current record's "website" value
 * @method UserConfigSettings setYoutube()                          Sets the current record's "youtube" value
 * @method UserConfigSettings setImage()                            Sets the current record's "image" value
 * @method UserConfigSettings setUser()                             Sets the current record's "User" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserConfigSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_config_settings');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('receive_notification_quizz_taken', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('top_logo_image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('logo_text', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('homepage_text', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('card_info', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('footer_info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('skype', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('facebook', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('youtube', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $imagebuilder0 = new Doctrine_Template_ImageBuilder(array(
             ));
        $this->actAs($imagebuilder0);
    }
}