<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Redirect301', 'doctrine');

/**
 * BaseRedirect301
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url_from
 * @property string $url_to
 * @property boolean $is_active
 * @property string $comment
 * @property integer $use_count
 * 
 * @method string      getUrlFrom()   Returns the current record's "url_from" value
 * @method string      getUrlTo()     Returns the current record's "url_to" value
 * @method boolean     getIsActive()  Returns the current record's "is_active" value
 * @method string      getComment()   Returns the current record's "comment" value
 * @method integer     getUseCount()  Returns the current record's "use_count" value
 * @method Redirect301 setUrlFrom()   Sets the current record's "url_from" value
 * @method Redirect301 setUrlTo()     Sets the current record's "url_to" value
 * @method Redirect301 setIsActive()  Sets the current record's "is_active" value
 * @method Redirect301 setComment()   Sets the current record's "comment" value
 * @method Redirect301 setUseCount()  Sets the current record's "use_count" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRedirect301 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('redirect301');
        $this->hasColumn('url_from', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('url_to', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('use_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}