<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Wiki', 'doctrine');

/**
 * BaseWiki
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $content
 * @property integer $sort_order
 * @property boolean $is_published
 * 
 * @method string  getName()         Returns the current record's "name" value
 * @method string  getContent()      Returns the current record's "content" value
 * @method integer getSortOrder()    Returns the current record's "sort_order" value
 * @method boolean getIsPublished()  Returns the current record's "is_published" value
 * @method Wiki    setName()         Sets the current record's "name" value
 * @method Wiki    setContent()      Sets the current record's "content" value
 * @method Wiki    setSortOrder()    Sets the current record's "sort_order" value
 * @method Wiki    setIsPublished()  Sets the current record's "is_published" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWiki extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wiki');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('sort_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}