<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Testaurus', 'doctrine');

/**
 * BaseTestaurus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $image
 * 
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method string    getImage()       Returns the current record's "image" value
 * @method Testaurus setName()        Sets the current record's "name" value
 * @method Testaurus setDescription() Sets the current record's "description" value
 * @method Testaurus setImage()       Sets the current record's "image" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestaurus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('testaurus');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $imagebuilder0 = new Doctrine_Template_ImageBuilder();
        $attach0 = new Doctrine_Template_Attach(array(
             'mime_types' => 
             array(
              0 => 'application/x-rar-compressed',
              1 => 'application/octet-stream',
              2 => 'application/zip',
             ),
             ));
        $meta0 = new Doctrine_Template_Meta();
        $geo0 = new Doctrine_Template_Geo();
        $this->actAs($imagebuilder0);
        $this->actAs($attach0);
        $this->actAs($meta0);
        $this->actAs($geo0);
    }
}