<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiteVisitPage', 'doctrine');

/**
 * BaseSiteVisitPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_visit_id
 * @property string $url
 * @property SiteVisit $SiteVisit
 * 
 * @method integer       getSiteVisitId()   Returns the current record's "site_visit_id" value
 * @method string        getUrl()           Returns the current record's "url" value
 * @method SiteVisit     getSiteVisit()     Returns the current record's "SiteVisit" value
 * @method SiteVisitPage setSiteVisitId()   Sets the current record's "site_visit_id" value
 * @method SiteVisitPage setUrl()           Sets the current record's "url" value
 * @method SiteVisitPage setSiteVisit()     Sets the current record's "SiteVisit" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteVisitPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_visit_page');
        $this->hasColumn('site_visit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteVisit', array(
             'local' => 'site_visit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}