<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserConfigDesign', 'doctrine');

/**
 * BaseUserConfigDesign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $header1_color
 * @property string $header2_color
 * @property string $header3_color
 * @property string $header4_color
 * @property string $link_color
 * @property string $text_color
 * @property string $top_background_color
 * @property string $top_text_color
 * @property string $top_text2_color
 * @property string $bottom_background_color
 * @property string $bottom_background_color2
 * @property string $bottom_text_color
 * @property string $bottom_text2_color
 * @property string $button1_background_color
 * @property string $button1_text_color
 * @property string $button2_background_color
 * @property string $button2_text_color
 * @property string $bottom_link_color
 * @property string $quizz_text_color
 * @property sfGuardUser $User
 * 
 * @method integer          getUserId()                   Returns the current record's "user_id" value
 * @method string           getHeader1Color()             Returns the current record's "header1_color" value
 * @method string           getHeader2Color()             Returns the current record's "header2_color" value
 * @method string           getHeader3Color()             Returns the current record's "header3_color" value
 * @method string           getHeader4Color()             Returns the current record's "header4_color" value
 * @method string           getLinkColor()                Returns the current record's "link_color" value
 * @method string           getTextColor()                Returns the current record's "text_color" value
 * @method string           getTopBackgroundColor()       Returns the current record's "top_background_color" value
 * @method string           getTopTextColor()             Returns the current record's "top_text_color" value
 * @method string           getTopText2Color()            Returns the current record's "top_text2_color" value
 * @method string           getBottomBackgroundColor()    Returns the current record's "bottom_background_color" value
 * @method string           getBottomBackgroundColor2()   Returns the current record's "bottom_background_color2" value
 * @method string           getBottomTextColor()          Returns the current record's "bottom_text_color" value
 * @method string           getBottomText2Color()         Returns the current record's "bottom_text2_color" value
 * @method string           getButton1BackgroundColor()   Returns the current record's "button1_background_color" value
 * @method string           getButton1TextColor()         Returns the current record's "button1_text_color" value
 * @method string           getButton2BackgroundColor()   Returns the current record's "button2_background_color" value
 * @method string           getButton2TextColor()         Returns the current record's "button2_text_color" value
 * @method string           getBottomLinkColor()          Returns the current record's "bottom_link_color" value
 * @method string           getQuizzTextColor()           Returns the current record's "quizz_text_color" value
 * @method sfGuardUser      getUser()                     Returns the current record's "User" value
 * @method UserConfigDesign setUserId()                   Sets the current record's "user_id" value
 * @method UserConfigDesign setHeader1Color()             Sets the current record's "header1_color" value
 * @method UserConfigDesign setHeader2Color()             Sets the current record's "header2_color" value
 * @method UserConfigDesign setHeader3Color()             Sets the current record's "header3_color" value
 * @method UserConfigDesign setHeader4Color()             Sets the current record's "header4_color" value
 * @method UserConfigDesign setLinkColor()                Sets the current record's "link_color" value
 * @method UserConfigDesign setTextColor()                Sets the current record's "text_color" value
 * @method UserConfigDesign setTopBackgroundColor()       Sets the current record's "top_background_color" value
 * @method UserConfigDesign setTopTextColor()             Sets the current record's "top_text_color" value
 * @method UserConfigDesign setTopText2Color()            Sets the current record's "top_text2_color" value
 * @method UserConfigDesign setBottomBackgroundColor()    Sets the current record's "bottom_background_color" value
 * @method UserConfigDesign setBottomBackgroundColor2()   Sets the current record's "bottom_background_color2" value
 * @method UserConfigDesign setBottomTextColor()          Sets the current record's "bottom_text_color" value
 * @method UserConfigDesign setBottomText2Color()         Sets the current record's "bottom_text2_color" value
 * @method UserConfigDesign setButton1BackgroundColor()   Sets the current record's "button1_background_color" value
 * @method UserConfigDesign setButton1TextColor()         Sets the current record's "button1_text_color" value
 * @method UserConfigDesign setButton2BackgroundColor()   Sets the current record's "button2_background_color" value
 * @method UserConfigDesign setButton2TextColor()         Sets the current record's "button2_text_color" value
 * @method UserConfigDesign setBottomLinkColor()          Sets the current record's "bottom_link_color" value
 * @method UserConfigDesign setQuizzTextColor()           Sets the current record's "quizz_text_color" value
 * @method UserConfigDesign setUser()                     Sets the current record's "User" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserConfigDesign extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_config_design');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('header1_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('header2_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('header3_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('header4_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('link_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('top_background_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('top_text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('top_text2_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('bottom_background_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('bottom_background_color2', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('bottom_text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('bottom_text2_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('button1_background_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('button1_text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('button2_background_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('button2_text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('bottom_link_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('quizz_text_color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}