<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiteMessage', 'doctrine');

/**
 * BaseSiteMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $type
 * @property string $name
 * @property string $phone_number
 * @property string $email
 * @property string $company_name
 * @property string $message
 * 
 * @method enum        getType()         Returns the current record's "type" value
 * @method string      getName()         Returns the current record's "name" value
 * @method string      getPhoneNumber()  Returns the current record's "phone_number" value
 * @method string      getEmail()        Returns the current record's "email" value
 * @method string      getCompanyName()  Returns the current record's "company_name" value
 * @method string      getMessage()      Returns the current record's "message" value
 * @method SiteMessage setType()         Sets the current record's "type" value
 * @method SiteMessage setName()         Sets the current record's "name" value
 * @method SiteMessage setPhoneNumber()  Sets the current record's "phone_number" value
 * @method SiteMessage setEmail()        Sets the current record's "email" value
 * @method SiteMessage setCompanyName()  Sets the current record's "company_name" value
 * @method SiteMessage setMessage()      Sets the current record's "message" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_message');
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'contact',
              1 => 'wishlist',
             ),
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('company_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $attach0 = new Doctrine_Template_Attach(array(
             'mime_types' => '*',
             ));
        $backendviewed0 = new Doctrine_Template_BackendViewed();
        $this->actAs($timestampable0);
        $this->actAs($attach0);
        $this->actAs($backendviewed0);
    }
}