<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BannedIp', 'doctrine');

/**
 * BaseBannedIp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * @property string $reason
 * 
 * @method string   getIp()     Returns the current record's "ip" value
 * @method string   getReason() Returns the current record's "reason" value
 * @method BannedIp setIp()     Sets the current record's "ip" value
 * @method BannedIp setReason() Sets the current record's "reason" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannedIp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banned_ip');
        $this->hasColumn('ip', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('reason', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}