<?php

/**
 * BaseQuizzQuestionAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quizz_question_id
 * @property string $name
 * @property boolean $is_correct
 * @property QuizzQuestion $QuizzQuestion
 * 
 * @method integer             getQuizzQuestionId()   Returns the current record's "quizz_question_id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method boolean             getIsCorrect()         Returns the current record's "is_correct" value
 * @method QuizzQuestion       getQuizzQuestion()     Returns the current record's "QuizzQuestion" value
 * @method QuizzQuestionAnswer setQuizzQuestionId()   Sets the current record's "quizz_question_id" value
 * @method QuizzQuestionAnswer setName()              Sets the current record's "name" value
 * @method QuizzQuestionAnswer setIsCorrect()         Sets the current record's "is_correct" value
 * @method QuizzQuestionAnswer setQuizzQuestion()     Sets the current record's "QuizzQuestion" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizzQuestionAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quizz_question_answer');
        $this->hasColumn('quizz_question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_correct', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QuizzQuestion', array(
             'local' => 'quizz_question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}