<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsRuntimeError', 'doctrine');

/**
 * BaseCmsRuntimeError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property string $url
 * 
 * @method string          getDescription() Returns the current record's "description" value
 * @method string          getUrl()         Returns the current record's "url" value
 * @method CmsRuntimeError setDescription() Sets the current record's "description" value
 * @method CmsRuntimeError setUrl()         Sets the current record's "url" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsRuntimeError extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_runtime_error');
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}