<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsLanguage', 'doctrine');

/**
 * BaseCmsLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $is_active
 * 
 * @method string      getName()      Returns the current record's "name" value
 * @method boolean     getIsActive()  Returns the current record's "is_active" value
 * @method CmsLanguage setName()      Sets the current record's "name" value
 * @method CmsLanguage setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_language');
        $this->hasColumn('name', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}