<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiteVisit', 'doctrine');

/**
 * BaseSiteVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip_address
 * @property string $country
 * @property string $user_agent
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Doctrine_Collection $VisitPages
 * 
 * @method string              getIpAddress()  Returns the current record's "ip_address" value
 * @method string              getCountry()    Returns the current record's "country" value
 * @method string              getUserAgent()  Returns the current record's "user_agent" value
 * @method integer             getUserId()     Returns the current record's "user_id" value
 * @method sfGuardUser         getUser()       Returns the current record's "User" value
 * @method Doctrine_Collection getVisitPages() Returns the current record's "VisitPages" collection
 * @method SiteVisit           setIpAddress()  Sets the current record's "ip_address" value
 * @method SiteVisit           setCountry()    Sets the current record's "country" value
 * @method SiteVisit           setUserAgent()  Sets the current record's "user_agent" value
 * @method SiteVisit           setUserId()     Sets the current record's "user_id" value
 * @method SiteVisit           setUser()       Sets the current record's "User" value
 * @method SiteVisit           setVisitPages() Sets the current record's "VisitPages" collection
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteVisit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_visit');
        $this->hasColumn('ip_address', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('country', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('user_agent', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('SiteVisitPage as VisitPages', array(
             'local' => 'id',
             'foreign' => 'site_visit_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}