generator:
  class: myDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 my_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item_menu_root
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: tmListRoot
        display: [name]
        batch_actions: {}
        actions: {}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
