<?php

/**
 * AppErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppErrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppError');
    }
}