<?php

/**
 * AppError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AppError extends BaseAppError
{
    public static function fire($message)
    {
        $event = new self;
        $event->setDescription($message);
        $event->save();
    }
}