<?php

/**
 * ApplicationRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicationRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicationRequest');
    }
}