<?php

/**
 * BannedIpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannedIpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannedIpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannedIp');
    }
}