<?php

/**
 * CmsLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsLanguageTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CmsLanguageTable
     */
    protected static $active_array = null;

    public static function getInstance() {
        return Doctrine_Core::getTable('CmsLanguage');
    }

    public static function getActiveArray() {
        if (!self::$active_array) {
            self::$active_array = array();
            foreach (self::getInstance()->createQuery('l')
                    ->where('l.is_active = ?', true)
                    ->execute() as $lang) {
                self::$active_array[] = $lang->getName();
            }
        }
        return self::$active_array;
    }

}