<?php

/**
 * CmsRuntimeErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsRuntimeErrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsRuntimeErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsRuntimeError');
    }
}