<?php

/**
 * ConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Config');
    }
    
    public function tmListUser(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->where("$a.display = ?", 'user');
        return $q;
    }
    
    public function tmListSystem(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->where("$a.display = ?", 'system');
        return $q;
    }    
    
    public function tmListDictionary(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->where("$a.section = ?", 'dictionary');        
        return $q;
    }
}