<?php

/**
 * EmailErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailErrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailError');
    }
}