<?php

/**
 * ForgotPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForgotPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForgotPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForgotPassword');
    }
}