<?php

/**
 * Localization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Localization extends BaseLocalization
{
    public function retrieveObject()
    {
        return Q::f($this->getModel(), $this->getPk());
    }
    
    public function loadValue($lang)
    {
        $object = $this->retrieveObject();
        if(!$object){
            return 'error';
        }
        if($object->getTable()->hasTemplate('Sluggable')){
            $options = $object->getTable()->getTemplate('Sluggable')->getOptions();
            $object->set($options['name'], '');
        }
        
        $val = trim($this->get($lang));
        if($val){
            $object->set($this->getField(), $this->get($lang));
            $object->save();
            return 'ok';
        }else{
            $object->set($this->getField(), $this->get('ru'));
            $object->save();
            return 'warning';            
        }
    }
}