<?php

/**
 * MenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MenuItem extends BaseMenuItem
{
    public function save(Doctrine_Connection $conn = null)
    {
        if($this->isNew()){
            if(MyConfig::get('menu_create_page') == 1){
                $page = new Page;
                $page->setName($this->getName());
                $page->setSlug(ProjectHelper::rus_to_slugify($this->getName()));
                $page->save();
                
                $this->setType('page');
                $this->setPageId($page->getId());
            }
        }
        parent::save($conn);        
    }
    
    public function getCmsModule() {
        return Q::f('CmsModule', $this->getCmsModuleId());
    }
}