<?php

/**
 * MenuItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MenuItem');
    }
    
    public function tmListRoot(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->andWhere("$a.level = ?", 0);
        return $q;
    }
    
    public function tmList(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->where("$a.root_id = ?", sfContext::getInstance()->getRequest()->getParameter('param'))
                //->andWhere("$a.level <> ?", 0)
                ;
        return $q;
    }
}