<?php

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage
{
    
    public function isSecure()
    {
        foreach($this->getMenuItems() as $item){
            if($item->getIsAuth())
                return true;
        }
        return false;
    }
    
    public function getReplaced($field, $replacements = null)
    {
        $content = $this->_get($field);
        if(!$replacements){
            return $content;
        }
        $reps = SiteEvent::extractReplacements($content);
        $reps_array = array();
        foreach($reps as $name)
        {
           $reps_array['{%' . $name . '%}'] = $replacements[$name];
        }
        return strtr($content, $reps_array);
    }    
}