<?php

/**
 * PageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object PageTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('Page');
	}

	public static function findOneBySpecialMark($special_mark) {
		return self::getInstance()->createQuery('p')->
						where('p.special_mark = ?', $special_mark)
						->fetchOne();
	}
	
	public function tmListCms(Doctrine_Query $q) {
		$a = $q->getRootAlias();
		$q->addWhere("$a.is_visible_for_admin = ?", true);
		return $q;
	}

}