<?php

/**
 * QuizzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quizz');
    }

    public function tmList(Doctrine_Query $q) {

        $a = $q->getRootAlias();
        $q->andWhere("$a.user_id = ?", sfContext::getInstance()->getUser()->getGuardUser()->getId());

        return $q;
    }
}