<?php

/**
 * QuizzQuestionAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizzQuestionAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizzQuestionAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizzQuestionAnswer');
    }
}