<?php

/**
 * QuizzTakeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizzTakeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizzTakeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizzTake');
    }
	
	public static function sfeventMigrateFromCookie(sfEvent $event) {
		$params = $event->getParameters();
		
		extract($params);//User, UserCookie
		
		Q::c('QuizzTake', 't')
				->where('t.user_cookie_id = ?', $UserCookie->id)
				->addWhere('t.user_id IS NULL')
				->update()
				->set('user_id', $User->id)
				->execute()
				;
		
	}
}