<?php

/**
 * QuizzQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizzQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizzQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizzQuestion');
    }
}