<?php

/**
 * Quizz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Quizz extends BaseQuizz
{
	protected $_is_passed = null;
	public $QuizzTake = null;

	public static function getDisplayTypes(){
	    return array(
	        'one' => 'One at a time',
            'all' => 'All at once'
        );
    }

	public function isPassed($reload = false) {
		if(is_null($this->_is_passed) || $reload){
			$passed = false;
			$q = Q::c('QuizzTake', 't')
					->where('t.quizz_id = ?', $this->id)
					;
			if(sfContext::getInstance()->getUser()->isAuthenticated()){
				$q2 = clone $q;
				$this->QuizzTake = $q2->addWhere('t.user_id = ?', sfContext::getInstance()->getUser()->getGuardUser()->id)
						->fetchOne()
						;
			}
			if(!$this->QuizzTake){
				$this->QuizzTake = $q->addWhere('t.user_cookie_id = ?', sfContext::getInstance()->getUser()->getUserCookie()->id)
					->fetchOne();
			}
			$this->_is_passed = (bool)$this->QuizzTake;
		}
		return $this->_is_passed;
	}
	
	public function getResults() {
		if($this->isPassed()){
			return unserialize($this->QuizzTake->info);
		}
		return null;
	}

	public function getUsername(){
	    return $this->getUserId() ? $this->getUser()->getUsername() : 'guest';
    }
	
	
}