<?php

/**
 * Redirect301
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Redirect301 extends BaseRedirect301
{
    public static function getRequestUri()
    {
        $request_uri = str_replace(array('index.php/', 'frontend_dev.php/', 'index.php', 'frontend_dev.php'), '', $_SERVER['REQUEST_URI']);
        if($request_uri == ''){
            $request_uri = '/';
        }
        return $request_uri;
    }
    public static function process()
    {
        $request_uri = self::getRequestUri();
        $redirect301 = Q::c('Redirect301', 'r')
                ->where('r.url_from = ?', $request_uri)
                ->andWhere('r.is_active = ?', true)
                ->fetchOne();
        if($redirect301){
            $redirect301->exec();
        }                 
    }
    
    public function exec()
    {
        $url_to = $this->getUrlTo();
        if($url_to == ''){
            $url_to = '/';
        }
        if(self::getRequestUri() != $url_to){
            $this->setUseCount($this->getUseCount() + 1);
            $this->save();
            sfContext::getInstance()->getController()->redirect($url_to, 0, 301);
        }
    }  
}