<?php

/**
 * Redirect301Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Redirect301Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Redirect301Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Redirect301');
    }
}