<?php

/**
 * SiteMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteMessage');
    }
}