<?php

/**
 * SiteEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteEvent');
    }
    
    public function tmList(Doctrine_Query $q)
    {
        $a = $q->getRootAlias();
        $q->andWhereIn("$a.type", array('contactus_message'), true);
        return $q;
    }
}