<?php

/**
 * SiteVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SiteVisit extends BaseSiteVisit {

    public static function executeVisit() {
        $user = sfContext::getInstance()->getUser();
        $visit = $user->getAttribute('site_visit', null);
        if (!$visit) {
            $visit = new self;
            $visit->fromArray(array(
                'ip_address' => $_SERVER['REMOTE_ADDR'],
                'user_agent' => $_SERVER['HTTP_USER_AGENT']
            ));
            $visit->save();
            $user->setAttribute('site_visit', $visit);
        }

        return $visit;
    }

    public static function processUrl($url) {
        $visit = self::executeVisit();
        if (sfConfig::get('app_visit_process_page', false)) {
            $visit_page = new SiteVisitPage;
            $visit_page->fromArray(array(
                'site_visit_id' => $visit->getId(),
                'url' => $url
            ));
            $visit_page->save();
        }
    }

}