<?php

/**
 * SiteVisitPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteVisitPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteVisitPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteVisitPage');
    }
}