<?php

/**
 * SocialBridge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SocialBridge extends BaseSocialBridge
{
    protected $networks = array(
        'facebook' => 'Facebook',
        'vkontakte' => 'Vkontakte',
        'google' => 'Google+',
        'mailru' => 'Mail.ru',
        'yandex' => 'Yandex',
        'twitter' => 'Twitter'
    );
    public function userConfirmEmail()
    {
        $url = sfContext::getInstance()->getRouting()->generate('oauth_bridge_confirm', array('token' => $this->getToken()), true);
        SiteEvent::fire('social_bridge_user_confirm_email', $this, array(
            'link' => "<a href='$url'>" . T::__('Подтвердить email аккаунт!') . "</a>"
        ));
        
        $this->setStatus('processing');
        $this->save();
    }
    
    public function confirmToken()
    {
        
        $user = $this->getUser();
        $s_user = $user->getSocialUser();
        $s_user->setEmail($user->getEmailAddress());
        
        $s_user->setUserId($user->getId());
        $s_user->set($this->getNetwork() . '_user_id', $this->getNetworkUserId());
        $s_user->save();
        
        sfContext::getInstance()->getUser()->signIn($user);
        
        $this->setStatus('closed');
        $this->save();
    }
    
    public function toArray($deep = true, $prefixKey = false)
    {
        $arr = parent::toArray($deep, $prefixKey);
        $arr['network_name'] = $this->networks[$this->getNetwork()];
        return $arr;
    }
    
    public function getNetworkName() {
        return $this->networks[$this->getNetwork()];
    }
}