<?php

/**
 * SocialUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocialUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocialUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SocialUser');
    }
}