<?php

/**
 * SocialBridgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SocialBridgeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SocialBridgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SocialBridge');
    }
}