<?php

/**
 * TestaurusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TestaurusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TestaurusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Testaurus');
    }
}