<?php

/**
 * UserConfigDesignTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserConfigDesignTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserConfigDesignTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserConfigDesign');
    }
}