<?php

/**
 * UserConfigSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserConfigSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserConfigSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserConfigSettings');
    }
}