<?php

/**
 * WikiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WikiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WikiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wiki');
    }
}