generator:
  class: myDoctrineGenerator
  param:
    model_class:           QuizzTake
    theme:                 my_admin_lanceng
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quizz_take
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: {label: Date/time}
        percentage: {label: 'Score, %'}
      list:
        object_actions:
          show: {label: Show, action: show, params: {class: 'btn btn-default system_popup_link', style: 'font-size: 10px'}}
          _delete: ~
        actions:
          back: {action: back, label: Back to my Quizzes, params: {class: 'btn btn-default'}}
#          back: {action: back, label: Back to Quizzes list, params: {class: 'btn btn-default'}, icon: cog}
        batch_actions: {}
        display: [created_at, User, percentage]
      filter:
        display: [quizz_id]
      form:    ~
      edit:    ~
      new:     ~
      
#    extra:
#      export:
#        filename: '%date% - My export'
#        mode: 'csv'      #[csv, xlsx]
#        dateformat: 'Y.m.d'
#        encoding: 'windows-1251'
#      javascript:
#        ajax_form_validation: #22.10.2014
#          fields: [name, email, directory]
#        remoteoptions:
#          purchase:
#            trigger: purchase_id
#            url: util/purchasePriceByPurchase
#            update: purchase_price_id
#        remotedata:
#          customer:
#            trigger: customer_id
#            url: util/remoteCustomerData
#            fields: [customer_name, customer_address]  
#        showhide_form_fields:
#          selloff:
#            toggler: selloff_enabled
#            fields: [selloff_price, selloff_end_date]
#           #reverse: true
#        showhide_selects:
#          type:
#            toggler: type
#            values:
#              default: []
#              articles: [articles]
#              category: [category_discount, categories_list]
