<?php

require_once dirname(__FILE__).'/../lib/user_config_settingsGeneratorConfiguration.class.php';
require_once dirname(__FILE__).'/../lib/user_config_settingsGeneratorHelper.class.php';

/**
 * user_config_settings actions.
 *
 * @package    cms
 * @subpackage user_config_settings
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class user_config_settingsActions extends autoUser_config_settingsActions
{
    public function preExecute(){
        if(!$this->getUser()->isSuper()){
            if(!in_array($this->getContext()->getActionName(), array('edit', 'update'))){
                $user = $this->getUser()->getGuardUser();
                $settings = $user->getUserConfigSettings();
                if(!$settings->getId()){
                    $settings->save();
                }
                return $this->redirect('user_config_settings/edit?id=' . $settings->getId());
            }
        }
        parent::preExecute();
    }

    public function executeEdit(sfWebRequest $request)
    {
        if(!$this->getUser()->isSuper()) {
            $object = $this->getRoute()->getObject();
            $user = $this->getUser()->getGuardUser();
            if($object->user_id != $user->id){
                return $this->forward404();
            }
        }
        parent::executeEdit($request); // TODO: Change the autogenerated stub
    }
    public function executeUpdate(sfWebRequest $request)
    {
        if(!$this->getUser()->isSuper()) {
            $object = $this->getRoute()->getObject();
            $user = $this->getUser()->getGuardUser();
            if($object->user_id != $user->id){
                return $this->forward404();
            }
        }
        parent::executeUpdate($request); // TODO: Change the autogenerated stub
    }
}
