<?php

require_once dirname(__FILE__).'/../lib/quizz_takeGeneratorConfiguration.class.php';
require_once dirname(__FILE__).'/../lib/quizz_takeGeneratorHelper.class.php';

/**
 * quizz_take actions.
 *
 * @package    cms
 * @subpackage quizz_take
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class quizz_takeActions extends autoQuizz_takeActions
{

    public function preExecute()
    {
        parent::preExecute(); // TODO: Change the autogenerated stub
        $filters = $this->getFilters();
        if(empty($filters['quizz_id'])){
            return $this->redirect('quizz/index');
        }
        $this->Quizz = Q::f('Quizz', $filters['quizz_id']);
        if(!$this->Quizz || !$this->getUser()->isMy($this->Quizz)){
            return $this->redirect('quizz/index');
        }
    }

    public function executeBack(){
        return $this->redirect('quizz/index');
    }

    public function executeShow(sfWebRequest $request) {
		$this->QuizzTake = $this->getRoute()->getObject();
		$this->Results = unserialize($this->QuizzTake->getInfo());
	}
}
