generator:
  class: myDoctrineGenerator
  param:
    model_class:           Todo
    theme:                 my_admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          todo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, created_at, updated_at]
        table_method: tmList
        title: ToDo
        batch_actions: {}
      filter:
      form:    ~
      edit:
        title: Править ToDo
      new:
        title: Создать ToDo
      
#    extra:
#      export:
#        filename: '%date% - My export'
#        mode: 'csv'      #[csv, xlsx]
#        dateformat: 'Y.m.d'
#        encoding: 'windows-1251'
#      javascript:
#        ajax_form_validation: #22.10.2014
#          fields: [name, email, directory]
#        remoteoptions:
#          purchase:
#            trigger: purchase_id
#            url: util/purchasePriceByPurchase
#            update: purchase_price_id
#        remotedata:
#          customer:
#            trigger: customer_id
#            url: util/remoteCustomerData
#            fields: [customer_name, customer_address]  
#        showhide_form_fields:
#          selloff:
#            toggler: selloff_enabled
#            fields: [selloff_price, selloff_end_date]
