<?php

require_once dirname(__FILE__).'/../lib/user_userGeneratorConfiguration.class.php';
require_once dirname(__FILE__).'/../lib/user_userGeneratorHelper.class.php';

/**
 * user_user actions.
 *
 * @package    cms
 * @subpackage user_user
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 23810 2009-11-12 11:07:44Z Kris.Wallsmith $
 */
class user_userActions extends autoUser_userActions
{
    public function preExecute(){
        if(!$this->getUser()->isSuper()){
            if(!in_array($this->getContext()->getActionName(), array('edit', 'update'))){
                $user = $this->getUser()->getGuardUser();
                return $this->redirect('user_user/edit?id=' . $user->getId());
            }
        }
        parent::preExecute();
    }

    public function executeEdit(sfWebRequest $request)
    {
        if(!$this->getUser()->isSuper()) {
            $object = $this->getRoute()->getObject();
            $user = $this->getUser()->getGuardUser();
            if($object->id != $user->id){
                return $this->forward404();
            }
        }
        parent::executeEdit($request); // TODO: Change the autogenerated stub
    }
    public function executeUpdate(sfWebRequest $request)
    {
        if(!$this->getUser()->isSuper()) {
            $object = $this->getRoute()->getObject();
            $user = $this->getUser()->getGuardUser();
            if($object->id != $user->id){
                return $this->forward404();
            }
        }
        parent::executeUpdate($request); // TODO: Change the autogenerated stub
    }
}
