application_request:
  class: sfDoctrineRouteCollection
  options:
    model:                ApplicationRequest
    module:               application_request
    prefix_path:          /application_request
    column:               id
    with_wildcard_routes: true

sf_guard_user_user_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user_user
    prefix_path:          /user_user
    column:               id
    with_wildcard_routes: true

user_config_settings:
  class: sfDoctrineRouteCollection
  options:
    model:                UserConfigSettings
    module:               user_config_settings
    prefix_path:          /user_config_settings
    column:               id
    with_wildcard_routes: true

user_config_design:
  class: sfDoctrineRouteCollection
  options:
    model:                UserConfigDesign
    module:               user_config_design
    prefix_path:          /user_config_design
    column:               id
    with_wildcard_routes: true

quizz_take:
  class: myDoctrineRouteCollectionQuizz
  options:
    model:                QuizzTake
    module:               quizz_take
    prefix_path:          /quizz_take
    column:               id
    with_wildcard_routes: true

quizz_question:
  class: myDoctrineRouteCollectionQuizz
  options:
    model:                QuizzQuestion
    module:               quizz_question
    prefix_path:          /quizz_question
    column:               id
    with_wildcard_routes: true

quizz:
  class: myDoctrineRouteCollection
  options:
    model:                Quizz
    module:               quizz
    prefix_path:          /quizz
    column:               id
    with_wildcard_routes: true

testaurus:
  class: sfDoctrineRouteCollection
  options:
    model:                Testaurus
    module:               testaurus
    prefix_path:          /testaurus
    column:               id
    with_wildcard_routes: true

todo:
  class: sfDoctrineRouteCollection
  options:
    model:                Todo
    module:               todo_sys
    prefix_path:          /todo_sys
    column:               id
    with_wildcard_routes: true

redirect301:
  class: sfDoctrineRouteCollection
  options:
    model:                Redirect301
    module:               redirect301
    prefix_path:          /redirect301
    column:               id
    with_wildcard_routes: true

localization:
  class: sfDoctrineRouteCollection
  options:
    model:                Localization
    module:               localization
    prefix_path:          /localization
    column:               id
    with_wildcard_routes: true

text_block_text_block_sys:
  class: sfDoctrineRouteCollection
  options:
    model:                TextBlock
    module:               text_block_sys
    prefix_path:          /text_block_sys
    column:               id
    with_wildcard_routes: true

text_block:
  class: sfDoctrineRouteCollection
  options:
    model:                TextBlock
    module:               text_block
    prefix_path:          /text_block
    column:               id
    with_wildcard_routes: true

wiki:
  class: sfDoctrineRouteCollection
  options:
    model:                Wiki
    module:               wiki
    prefix_path:          /wiki
    column:               id
    with_wildcard_routes: true

email_error:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailError
    module:               email_error
    prefix_path:          /email_error
    column:               id
    with_wildcard_routes: true

config_settings_sys:
  class: sfDoctrineRouteCollection
  options:
    model:                Config
    module:               settings_sys
    prefix_path:          /settings_sys
    column:               id
    with_wildcard_routes: true

email_template:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailTemplate
    module:               email_template
    prefix_path:          /email_template
    column:               id
    with_wildcard_routes: true

default_image:
  class: sfDoctrineRouteCollection
  options:
    model:                DefaultImage
    module:               default_image
    prefix_path:          /default_image
    column:               id
    with_wildcard_routes: true

site_visit:
  class: sfDoctrineRouteCollection
  options:
    model:                SiteVisit
    module:               site_visit
    prefix_path:          /site_visit
    column:               id
    with_wildcard_routes: true

site_event:
  class: sfDoctrineRouteCollection
  options:
    model:                SiteEvent
    module:               site_event
    prefix_path:          /site_event
    column:               id
    with_wildcard_routes: true

site_message:
  class: sfDoctrineRouteCollection
  options:
    model:                SiteMessage
    module:               site_message
    prefix_path:          /site_message
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options: { model: sfGuardUser, module: user, prefix_path: /user, column: id, with_wildcard_routes: true }
config_dictionary:
  class: sfDoctrineRouteCollection
  options: { model: Config, module: dictionary, prefix_path: /dictionary, column: id, with_wildcard_routes: true }
config:
  class: sfDoctrineRouteCollection
  options: { model: Config, module: settings, prefix_path: /settings, column: id, with_wildcard_routes: true }
menu_item_menu_root:
  class: sfDoctrineRouteCollection
  options: { model: MenuItem, module: menu_root, prefix_path: /menu_root, column: id, with_wildcard_routes: true }
page:
  class: sfDoctrineRouteCollection
  options: { model: Page, module: page, prefix_path: /page, column: id, with_wildcard_routes: true }
menu_item_tree:
  url: '/menu/tree/root/:root'
  param: { module: menu, action: tree }
menu_item:
  class: sfDoctrineRouteCollection
  options: { model: MenuItem, module: menu, prefix_path: ':param/menu', column: id, with_wildcard_routes: true }
homepage:
  url: /
  param: { module: dashboard, action: index}
default_index:
  url: '/:module'
  param: { action: index }
default:
  url: '/:module/:action/*'
