CmsModule:
  connection: doctrine
  columns:
    name: {type: string(255), notnull: true, unique: true}
    is_active: {type: boolean, default: true}
    model: string(255)
    model_sitemap_callback: string(255)
    show_route: string(255)
    
CmsLanguage:
  connection: doctrine  
  columns:
    name: {type: string(5), notnull: true, unique: true}
    is_active: {type: boolean, default: true}
    
CmsRuntimeError:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    description: string()
    url: string()

Config:
  connection: doctrine  
  columns:
    name: {type: string(255), notnull: true}
    title: string(255)
    value: string()
    help: string()
    display: {type: enum, values: [user, system]}
    section: {type: enum, values: [settings, dictionary, system, wiki], default: settings}
    type: {type: enum, values: [integer, float, boolean, text, enum], default: text}
    type_enum_values: string()
    use_wysiwyg: {type: boolean, default: false}
    is_localized: {type: boolean, default: false}

UserConfigSettings:
  actAs: [ImageBuilder]
  connection: doctrine
  columns:
    user_id: {type: integer, notnull: true}
    receive_notification_quizz_taken: {type: boolean, default: false}
    top_logo_image: string(255)
    logo_text: string(255)
    html_title: string(255)
    homepage_text: string()
    card_info: string()
    footer_info: string(255)
    email: string(255)
    phone: string(255)
    skype: string(255)
    facebook: string(255)
    website: string(255)
    youtube: string(255)
    image: string(255)
  relations:
    User: {class: sfGuardUser, local: user_id, type: one, foreignType: one, onDelete: CASCADE}

UserConfigDesign:
  connection: doctrine
  columns:
    user_id: {type: integer, notnull: true}
    header1_color: string(32)
    header2_color: string(32)
    header3_color: string(32)
    header4_color: string(32)
    link_color: string(32)
    text_color: string(32)
    top_background_color: string(32)
    top_text_color: string(32)
    top_text2_color: string(32)
    bottom_background_color: string(32)
    bottom_background_color2: string(32)
    bottom_text_color: string(32)
    bottom_text2_color: string(32)
    button1_background_color: string(32)
    button1_text_color: string(32)
    button2_background_color: string(32)
    button2_text_color: string(32)
    bottom_link_color: string(32)
    quizz_text_color: string(32)
  relations:
    User: {class: sfGuardUser, local: user_id, type: one, foreignType: one, onDelete: CASCADE}


MenuItem:
  connection: doctrine
  actAs:
    NestedSet:
      hasManyRoots:   true
      rootColumnName: root_id
  columns:
    name: {type: string(255), notnull: true}
    root_name: string(255)
    type: {type: enum, values: [empty, page, module, route, external], default: empty}
    page_id: integer
    cms_module_id: integer
    route: string(255)
    external: string()
    is_empty: {type: boolean, default: true}
    is_auth: {type: boolean, default: false}
    icon_class: string(32)
  relations:
    Page: {foreignAlias: MenuItems, onDelete: SET NULL}
    
Page:
  connection: doctrine  
  actAs:
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
      builder: 'ProjectHelper::slug_builder'      
    Meta: ~
    Redirect301:
      field: slug
      route: page_show
  columns:
    name: {type: string(255), notnull: true}
    content: string()
    is_module_page: {type: boolean, default: false}
    module_name: string(255)
    is_content_editable: {type: boolean, default: true}
    special_mark: string(255)
    is_redirect: {type: boolean, default: false}
    redirect_route: {type: string(32), default: '/'}
    redirect_timeout: {type: integer(2), default: 5}
    layout: string(32)
    is_visible_for_admin: {type: boolean, default: true}
    
Profile:
  connection: doctrine  
  actAs:
    ImageBuilder: ~
    Timestampable: ~
    Geo:
      engine: google
  columns:
    user_id: {type: integer, notnull: true}
    first_name: string(255)
    last_name: string(255)
    image: string(255)
    dob: date
    email: string(255)
    phone: string(255)
    about: string()
  relations:
    User: {class: sfGuardUser, local: user_id, type: one, foreignType: one, onDelete: CASCADE}  

    
SiteMessage:
  connection: doctrine  
  actAs:
    Timestampable: ~
    Attach:
      mime_types: '*'
    BackendViewed: ~
  columns:
    type: {type: enum, values: [contact, wishlist]}
    name: {type: string(255), notnull: true}
    phone_number: string(255)
    email: string(255)
    company_name: string(255)
    message: string()
    
EmailTemplate:
  connection: doctrine  
  columns:
    name: {type: string(255), notnull: true}
    subject: {type: string(255), notnull: true}
    message: string()
    
SiteEvent:
  connection: doctrine  
  actAs: [Timestampable, BackendViewed]
  columns:
    type: {type: string(255)}
    description: string()
    admin_email: string()
    user_email: string()
    
AppError:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    description: string()    
    
SiteVisit:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    ip_address: string(32)
    country: string(32)
    user_agent: string(255)
    user_id: integer
  relations:
    User: {class: sfGuardUser, local: user_id, foreignAlias: SiteVisits, onDelete: SET NULL}    
    
SiteVisitPage:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    site_visit_id: {type: integer, notnull: true}
    url: string(255)
  relations:
    SiteVisit: {foreignAlias: VisitPages, onDelete: CASCADE}
    
ForgotPassword:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    user_id: {type: integer, notnull: true}
    email: {type: string(255), notnull: true}
    hash: {type: string(255), notnull: true}
  relations:
    User: {class: sfGuardUser, local: user_id, onDelete: CASCADE, foreignAlias: ForgotPasswords}  
    
    
DefaultImage:
  connection: doctrine  
  actAs: [ImageBuilder]
  columns:
    name: string(255)
    title: string(255)
    image: {type: string(255), notnull: true} 
    
    
Redirect301:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    url_from: {type: string(255), notnull: true, unique: true}
    url_to: {type: string(255), notnull: true}
    is_active: {type: boolean, default: true}
    comment: string()  
    use_count: {type: integer, default: 0}
    
    
EmailError:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    email_from: string(255)
    email_to: string(255)
    subject: string(255)
    body: string()
    cc: string(255)
    file: string(255)
    errmes: string()    
    
Wiki:
  connection: doctrine  
  columns:
    name: {type: string(255), notnull: true}
    content: string()
    sort_order: integer
    is_published: {type: boolean, default: false}
    
BannedIp:
  connection: doctrine  
  actAs: [Timestampable]
  columns:
    ip: {type: string(15), notnull: true}
    reason: string(255)
    
TextBlock:
  connection: doctrine
  actAs:
    I18n:
      fields: [text]
  columns:
    name: {type: string(255), notnull: true}
    title: {type: string(255)}
    text: string()
    application: string(32)
    module: string(32)
    special_mark: string(32)
    is_visible_for_admin: {type: boolean, default: false}
  indexes:
    section_index:
      fields: [application, module]
      
Localization:
  connection: doctrine  
  columns:
    model: {type: string(64), notnull: true}
    pk: {type: integer, notnull: true}
    field: {type: string(64), notnull: true}
    ru: string()
    en: string()
    de: string()
    es: string()
    it: string()
    fr: string()
    pt: string()    
    sv: string()    
    fi: string()    
    no: string()        
    nl: string()        
    pl: string()    
  indexes:
    main: 
      fields: [model, pk, field]
  
  
SocialUser:
  connection: doctrine  
  columns:
    facebook_user_id: decimal(21,0)
    facebook_user_info: string()
    vkontakte_user_id: decimal(21,0)
    vkontakte_user_info: string()    
    google_user_id: decimal(21,0)   
    google_user_info: string()
    mailru_user_id: decimal(21,0)
    mailru_user_info: string()
    yandex_user_id: decimal(21,0)
    yandex_user_info: string()
    twitter_user_id: decimal(21,0)  
    twitter_user_info: string()
    user_id: integer
    email: string(255)
  relations:
    User: {local: user_id, class: sfGuardUser, type: one, foreignType: one, onDelete: CASCADE} 
    
SocialBridge:
  connection: doctrine  
  actAs:
    Timestampable: ~
  columns:
    user_id: {type: integer, notnull: true}
    email: {type: string(64), notnull: true}
    status: {type: enum, values: [new, processing, closed], default: new}
    token: string(255)
    network: {type: enum, values: [facebook, vkontakte, mailru, google, yandex, twitter]}
    network_user_id: integer
  relations:
    User: {class: sfGuardUser, local: user_id, foreignAlias: SocialBridges, onDelete: CASCADE}   
    
UserCookie:
  actAs: [Timestampable]
  columns:
    cookie: string(80)
    user_id: integer
    keep_logged_in: {type: boolean, default: false}
  relations:
    User: {local: user_id, class: sfGuardUser, onDelete: SET NULL, type: one, foreignType: one}
  indexes:
    cookie:
      fields: [cookie]
    
Todo:
  connection: doctrine
  actAs: [Timestampable]
  columns:
    name: {type: string(), notnull: true}
    status: {type: enum, values: [open, closed], default: open}
    
Testaurus:
  connection: doctrine
  actAs:
    ImageBuilder: ~
    Attach:
      mime_types: [application/x-rar-compressed, application/octet-stream, application/zip]
    Meta: ~
    Geo: ~
  columns:
    name: {type: string(255), notnull: true}
    description: string()
    image: string(255)
    
    
Quizz:
  actAs:
    Timestampable: ~
    User:
      apps: [cms]
      cookie: false
    Sluggable:
      unique: false
      fields: [name]
      canUpdate: true
      builder: 'ProjectHelper::slug_builder'
  columns:
    name: {type: string(255)}
    description: string()
    display: {type: enum, values: [one, all], default: one}
    is_active: {type: boolean, default: true}
    
QuizzQuestion:
  columns:
    quizz_id: {type: integer, notnull: true}
    name: {type: string(), notnull: true}
    answer_mode: {type: enum, values: [select, select_other, other], default: select}
    comment: string()
  relations:
    Quizz: {foreignAlias: Questions, onDelete: CASCADE}
    
QuizzQuestionAnswer:
  columns:
    quizz_question_id: {type: integer, notnull: true}
    name: {type: string(255), notnull: true}
    is_correct: boolean
  relations:
    QuizzQuestion: {foreignAlias: Answers, onDelete: CASCADE}

    
QuizzTake:
  actAs:
    Timestampable: ~
    User: ~
    Event:
      create:
        frontend: quizz_take_create
    BackendViewed: ~
  columns:
    quizz_id: {type: integer, notnull: true}
    info: string()
    questions_count: {type: integer(2), unsigned: true}
    correct_answers_count: {type: integer(2), unsigned: true}
    percentage: {type: integer(2), unsigned: true}
  relations:
    Quizz: {onDelete: CASCADE, foreignAlias: QuizzTakes}

ApplicationRequest:
  actAs:
    Timestampable: ~
    Event:
      create:
        frontend: application_request_create
    BackendViewed: ~
  columns:
    name: {type: string(255), notnull: true}
    email: {type: string(255), notnull: true}
    channel: string(255)
    comment: string()