generator:
  class: myDoctrineGenerator
  param:
    model_class:           Testaurus
    theme:                 my_admin_lanceng
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          testaurus
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, _image, _attachment, meta_title]
      filter:
        display: [name]
      form:
        display:
          Main: [name, description]
          Image: [image]
          Attachment: [attach]
          Meta: [meta_title, meta_keywords, meta_description]    
          Map: [gmaps]              
      edit:    ~
      new:     ~
      
#    extra:
#      export:
#        filename: '%date% - My export'
#        mode: 'csv'      #[csv, xlsx]
#        dateformat: 'Y.m.d'
#        encoding: 'windows-1251'
#      javascript:
#        ajax_form_validation: #22.10.2014
#          fields: [name, email, directory]
#        remoteoptions:
#          purchase:
#            trigger: purchase_id
#            url: util/purchasePriceByPurchase
#            update: purchase_price_id
#        remotedata:
#          customer:
#            trigger: customer_id
#            url: util/remoteCustomerData
#            fields: [customer_name, customer_address]  
#        showhide_form_fields:
#          selloff:
#            toggler: selloff_enabled
#            fields: [selloff_price, selloff_end_date]
#           #reverse: true
#        showhide_selects:
#          type:
#            toggler: type
#            values:
#              default: []
#              articles: [articles]
#              category: [category_discount, categories_list]
